server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 1000
            response-timeout: 5s
          routes:
            - id: users
              uri: lb://users-service
              predicates:
                - Path=/api/users/**
              # sin StripPrefix: tu backend expone /api/users/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
