apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: microapps
spec:
  selector:
    app: users-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
