name: CD — Pull & Run on Self-Hosted (WSL)

on:
  workflow_dispatch:
    inputs:
      compose_file:
        description: "Compose override file to use for deployment"
        required: false
        default: "docker-compose.ci.yml"
  push:
    branches: ["main", "master"]
    paths:
      - ".github/workflows/cd.yml"
      - "docker-compose.ci.yml"

jobs:
  deploy:
    runs-on: [self-hosted, linux, wsl]

    # Put secrets in the JOB env, not at the workflow top level
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      COMPOSE_FILE_OVERRIDE: ${{ github.event.inputs.compose_file }} # defaults to the input's default

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login (optional if images are public)
        if: ${{ env.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Pull images & start services
        run: |
          set -euo pipefail
          FILE="${COMPOSE_FILE_OVERRIDE:-docker-compose.ci.yml}"
          docker compose -f docker-compose.yml -f "$FILE" pull
          docker compose -f docker-compose.yml -f "$FILE" up -d --remove-orphans
